import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Outfit } from 'next/font/google'
import './globals.css'

const outfitSans = Outfit({
  variable: '--font-outfit-sans',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfitSans.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}